#!/usr/bin/env bash
#
# Hetu one-shot installer for AWS.
#
# Designed for AWS CloudShell, so it works the same from Windows, macOS or Linux —
# open https://console.aws.amazon.com/cloudshell and run:
#
#   curl -sL https://hetu.run/install.sh | bash -s -- --region ap-southeast-2
#
# What this installs:
#   * Everything in ONE CloudFormation stack you can inspect or delete as a unit: an
#     App Runner service, an RDS Postgres holding your saved policy drafts, a Cognito
#     user pool for sign-in, and a private VPC for the database.
#   * The service's role is NOT the managed ReadOnlyAccess. It is scoped to authorization
#     configuration: IAM identities and their policies, Organizations SCPs and RCPs, and
#     the resource policies on buckets, keys, queues, topics, functions and secrets.
#     On your secrets it holds GetResourcePolicy and not GetSecretValue; on S3,
#     GetBucketPolicy and not GetObject. Hetu can tell you who could read a secret,
#     and cannot read it. (It does read one secret: the database password this stack
#     generated for it, scoped by ARN to that single secret.)
#
# Hetu installs into your own account rather than being a SaaS because service control
# policies live in your organisation's management account. Without them, "can this
# principal do that" is wrong in exactly the cases that matter.
#
# App Runner (rather than ECS behind a load balancer) because it gives a managed HTTPS
# endpoint with no certificate or domain of your own — and Cognito will not accept a
# plain-HTTP callback URL.
#
# Prerequisites:
#   * Permission to create CloudFormation stacks, IAM roles, RDS, Cognito and App Runner.
#
set -euo pipefail

STACK="hetu"
REGION=""; IMAGE=""; IMAGE_TYPE="ECR_PUBLIC"; ADMIN_EMAIL=""
# Published image. App Runner cannot pull from GHCR, so AWS installs use ECR Public.
IMAGE_REPO="public.ecr.aws/w4o8p5x9/hetu"
VERSION_URLS=(
  "https://hetu.run/version.json"
  "https://raw.githubusercontent.com/abhijitsghosh/hetu-deploy/main/version.json"
)
TEMPLATE_URLS=(
  "https://hetu.run/hetu-aws.yaml"
  "https://raw.githubusercontent.com/abhijitsghosh/hetu-deploy/main/hetu-aws.yaml"
)

# Resolve the released version and install THAT, rather than whatever ":latest" happens to
# point at while the install runs. "latest" is a mutable tag: a release rewrites it, and an
# install that reads it mid-rewrite gets an image nobody chose and cannot reproduce. Pinning
# also means the version a customer installed is the version they can be told to roll back to.
resolve_version() {
  local v=""
  for url in "${VERSION_URLS[@]}"; do
    v=$(curl -fsS "$url" 2>/dev/null | sed -n 's/.*"latest"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
    [[ -n "$v" && "$v" != "0.0.0" ]] && { echo "$v"; return 0; }
  done
  return 1
}

usage() {
  echo "Usage: install.sh --region <aws-region> [--stack <name>] [--image <uri>] [--image-type ECR|ECR_PUBLIC] [--admin-email <you@org.com>]"
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -r|--region)      REGION="${2:-}"; shift 2;;
    -s|--stack)       STACK="${2:-}"; shift 2;;
    -i|--image)       IMAGE="${2:-}"; shift 2;;
    --image-type)     IMAGE_TYPE="${2:-}"; shift 2;;
    -e|--admin-email) ADMIN_EMAIL="${2:-}"; shift 2;;
    -h|--help)        usage;;
    *) echo "Unknown option: $1"; usage;;
  esac
done
[[ -z "$REGION" ]] && usage
if [[ -z "$IMAGE" ]]; then
  if VERSION=$(resolve_version); then
    IMAGE="${IMAGE_REPO}:${VERSION}"
  else
    # The feed is unreachable, or no release has been published yet. Say so rather than
    # silently installing a moving tag.
    echo "WARNING: no published version found in the release feed; falling back to :latest."
    echo "         The installed version will not be pinned or reproducible."
    IMAGE="${IMAGE_REPO}:latest"
  fi
fi

command -v aws >/dev/null 2>&1 || { echo "ERROR: AWS CLI not found. Run this in AWS CloudShell."; exit 1; }
aws sts get-caller-identity >/dev/null 2>&1 || { echo "ERROR: not signed in to AWS."; exit 1; }

ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
echo "▶ Installing Hetu into AWS account: $ACCOUNT (region $REGION)"
echo "  stack: $STACK   image: $IMAGE"

# The database password is generated by Secrets Manager inside the stack — it is never a
# CLI argument, never a stack parameter, and never printed here.

TEMPLATE=$(mktemp)
for url in "${TEMPLATE_URLS[@]}"; do
  if curl -fsSL "$url" -o "$TEMPLATE" && [[ -s "$TEMPLATE" ]]; then break; fi
done
[[ -s "$TEMPLATE" ]] || { echo "ERROR: could not download the stack template."; exit 1; }

# ---------- [1/3] Stack ----------
echo "▶ [1/3] Deploying the stack — 10–15 min (the database is the slow part)…"
# On failure CloudFormation's own advice is to go and run describe-stack-events yourself,
# and the first CREATE_FAILED it lists is usually a resource that failed because something
# else did. Print the reasons here instead, oldest first, so the cause leads.
explain_failure() {
  echo ""
  echo "✖ The stack did not create. Reasons CloudFormation recorded, first cause first:"
  local reasons
  reasons=$(aws cloudformation describe-stack-events --region "$REGION" --stack-name "$STACK" \
    --query 'reverse(StackEvents[?ResourceStatus==`CREATE_FAILED` || ResourceStatus==`UPDATE_FAILED`].[LogicalResourceId,ResourceStatusReason])' \
    --output text 2>/dev/null | grep -v 'cancelled\|Resource creation cancelled' | head -5)
  if [[ -n "$reasons" ]]; then
    sed 's/^/    /' <<< "$reasons"
  else
    # An empty list is not "no reason" — it means the events are gone, usually because the
    # stack was deleted. Saying nothing here reads as a tool that failed to explain itself.
    echo "    (none recorded — the stack's events are no longer readable, which usually"
    echo "     means it has already been deleted. Re-run the install to reproduce.)"
  fi
  # App Runner's own reason is "review the application logs", which is no help when the
  # container never started and there are no application logs to review. Say where to look.
  if aws cloudformation describe-stack-events --region "$REGION" --stack-name "$STACK" \
       --query 'StackEvents[?ResourceStatus==`CREATE_FAILED`].LogicalResourceId' \
       --output text 2>/dev/null | grep -q '\bService\b'; then
    echo ""
    echo "  App Runner failed to start the container. If it reported pulling the image and"
    echo "  then failed with no /aws/apprunner/*/application log group at all, the container"
    echo "  never ran — check the service log group for the deployment events:"
    echo "    aws logs tail /aws/apprunner/${STACK}-app --region $REGION --since 1h"
  fi
  echo ""
  echo "  The stack is left in place so those events stay readable. A failed create leaves it"
  echo "  in ROLLBACK_COMPLETE, which cannot be updated — delete it before re-running install:"
  echo "    aws cloudformation delete-stack --region $REGION --stack-name $STACK"
  exit 1
}

aws cloudformation deploy \
  --region "$REGION" \
  --stack-name "$STACK" \
  --template-file "$TEMPLATE" \
  --capabilities CAPABILITY_NAMED_IAM \
  --parameter-overrides ContainerImage="$IMAGE" ImageRepositoryType="$IMAGE_TYPE" \
                        NamePrefix="$STACK" \
  --no-fail-on-empty-changeset || { rm -f "$TEMPLATE"; explain_failure; }
rm -f "$TEMPLATE"

out() { aws cloudformation describe-stacks --region "$REGION" --stack-name "$STACK" \
          --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text; }
APP_URL=$(out AppUrl); POOL_ID=$(out UserPoolId); CLIENT_ID=$(out UserPoolClientId)
ROLE=$(out InstanceRoleName)
echo "    app url: $APP_URL"

# ---------- [2/3] Sign-in callback ----------
# Only known once App Runner has a hostname, so it is set after the stack. Spring's OAuth2
# client uses /login/oauth2/code/{registrationId}, and Hetu's registration id is "oidc".
echo "▶ [2/3] Registering the sign-in callback…"
aws cognito-idp update-user-pool-client \
  --region "$REGION" --user-pool-id "$POOL_ID" --client-id "$CLIENT_ID" \
  --callback-urls "$APP_URL/login/oauth2/code/oidc" \
  --logout-urls "$APP_URL" \
  --allowed-o-auth-flows code --allowed-o-auth-scopes openid profile email \
  --allowed-o-auth-flows-user-pool-client \
  --supported-identity-providers COGNITO >/dev/null

# ---------- [3/3] First operator ----------
echo "▶ [3/3] Inviting the first operator…"
if [[ -n "$ADMIN_EMAIL" ]]; then
  aws cognito-idp admin-create-user --region "$REGION" --user-pool-id "$POOL_ID" \
    --username "$ADMIN_EMAIL" --user-attributes Name=email,Value="$ADMIN_EMAIL" \
                                                Name=email_verified,Value=true \
    --desired-delivery-mediums EMAIL >/dev/null 2>&1 \
    && echo "    invited $ADMIN_EMAIL (check your inbox for the temporary password)" \
    || echo "    (user already exists)"
else
  echo "    no --admin-email given. Invite yourself with:"
  echo "      aws cognito-idp admin-create-user --region $REGION --user-pool-id $POOL_ID \\"
  echo "        --username you@org.com --user-attributes Name=email,Value=you@org.com \\"
  echo "        Name=email_verified,Value=true --desired-delivery-mediums EMAIL"
fi

cat <<EOF

✅ Hetu is installed — everything is in CloudFormation stack '$STACK'.

   Open:   $APP_URL
   Sign in with the Cognito account invited above.
   Next:   paste a policy to see what it actually grants, or run a simulation to ask
           whether a principal can perform an action — and get back the statement that
           decided, not just a verdict.

   Hetu runs as '$ROLE', scoped to reading authorization configuration and nothing more.
   It never changes anything, and it never reads the contents of your data.

   Upgrade later (image only, keeps your saved drafts):
     curl -sL https://hetu.run/upgrade.sh | bash -s -- --region $REGION

   Tear down later (the database is snapshotted before deletion):
     aws cloudformation delete-stack --region $REGION --stack-name $STACK
EOF
